#!/bin/bash

num=0

while [ $num -le 11 ]; do
    echo "$num"
    num=$((num+2))
done

# Printing prime numbes uptil n

read -p "Enter the value of n: " n

echo "Odd numbers till $n is "
i=3
while [ $i -le $n ]; do
    if (( ((i%2)) != 0 )); then
        echo "$i"
    fi
    i=$((i+1))
done

# Reading the contents of a file via loops

while read day mon yr; do
    printf "Day: ${day}\nMonth: ${mon}\nYear: ${yr}\n"
done < file.txt
