#!/bin/bash


read -p "" a
read -p "" b
read -p "" c

if [[ $a == $b && $b == $c && $c == $a ]]; then
    echo "EQUILATERAL"
elif [[ $a != $b && $b != $c && $c != $a ]]; then
    echo "SCALENE"
else
    echo "ISOSCELES"
fi

